version: '3'
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: app/laravel
    container_name: news_app
    restart: always
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
      PHP_IDE_CONFIG: serverName=xdebug_api
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - mynet
    depends_on:
      - db
  nginx:
    image: nginx:alpine
    container_name: news_nginx
    restart: always
    tty: true
    ports:
      - '${APP_PORT:-80}:80' # Set any free port for local but also change nginx.conf
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - mynet
  db:
    image: mysql:8.0.25
    container_name: news_db
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - news_db:/var/lib/mysql
    ports:
      - '${FORWARD_DB_PORT:-3302}:3306' # Set any free port for local
    networks:
      - mynet

volumes:
  news_db:

networks:
  mynet:
    driver: bridge
